---
lenguage: python
python:
  - "2.7"

install:
  - "sudo pip install -r requerimientos.txt"
  - "sudo pip install --upgrade six"

before_script:
  - "autopep8 -ir *"

  - "flake8 --max-complexity=10 --exclude=*.txt,*.md,*.pyc,steps.py,*.feature *"


script:
  - "python figurastest.py"
  - lettuce
  - coverage run --branch figurastest.py
  - coverage report
